### ISSUE TITLE
Implement FMOD and footstep example

### ISSUE THREAD

**Issue by AstralEik** [PolarBearClan/Making-Games#10]
**Overview**
We are going to be using FMOD for managing our soundscape in the game. This task is about implementing FMOD, figuring out how it works and getting the footstep example we have been working on in the sound-workshop into the game.

**User story**
As a developer, I want to be able to add dynamic sounds to events in Unity, using FMOD and FMOD files to programmatically manage what sounds are played.

**Acceptance criteria**
- A developer is able to call a sound object in all scenes and make it play an FMOD sound file presents in a 'Audio' folder.
- FMOD properly functions (for example, managing the sounds played dynamically).
- There is a clear, proved and documented Audacity -> FMOD -> Unity -> Event asset pipeline.

**Full task description**

**Comment by Nickromancer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement FMOD and footstep example](https://trello.com/c/qex4EH8R/19-implement-fmod-and-footstep-example)
