### ISSUE TITLE
Bug: Logs are very hard to pick up due to camera angles

### ISSUE THREAD

**Issue by KristofLenard12** [PolarBearClan/Making-Games#115]
**Overview**
Logs are very hard to pick up due to camera angles

**Fix criteria**
- [ ] Make the camera pointable in any direction, not just a limited cone.

**Reproduction steps**
Step 1: Go to woodshed in Day1_Outside_Daytime
Step 2: Pick up wood.
Step 3: See it's very hard with some logs on the ground as the camera cannot be angled far enough down. 

**Full task description**

**Comment by ThePedroboy** [comment]
This can and will be solved when correct and final settings are set up in the FirstPersonController - there is a angle limitation too which will solve this.
