### ISSUE TITLE
Quests System - Action Tasks

### ISSUE THREAD

**Issue by ThePedroboy** [PolarBearClan/Making-Games#35]
**Overview**
Implement a quest of type 'do action X at place Y, Z times total'.
(Clean the cafeteria + Clean the library)
Action = Press E (Hold E for X seconds)

**User story**
As the player I want to be able to complete this type of quest.

**Acceptance criteria**
Visual effect of the location where the action is to be done.
System for actually doing the action (probably some extension of IInteractable).

**Comment by Nickromancer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Tasks/Quest system](https://trello.com/c/GcVV39c2/39-tasks-quest-system)
