### ISSUE TITLE
Quests System - Collectible Tasks

### ISSUE THREAD

**Issue by ThePedroboy** [PolarBearClan/Making-Games#36]
**Overview**
Implement a quest of type 'bring item X to place Y, Z times total'.
(Pick up firewood + Pick up flowers for sacrificial area)

**User story**
As the player I want to be able to complete this type of quest.

**Acceptance criteria**
Visual effect of the **dropout** location.
Items visible when carried.
Player is only able to hold 2 pieces of wood at a time.
Item not being able to pick up after delivery (to avoid cheesing).

**Comment by Nickromancer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Tasks/Quest system](https://trello.com/c/GcVV39c2/39-tasks-quest-system)
