### ISSUE TITLE
Lock/unlock doors

### ISSUE THREAD

**Issue by KristofLenard12** [PolarBearClan/Making-Games#63]
**Overview**
The ability to lock and unlock doors with keys.

**User story**
As a player, I want to be able to lock doors, so that I can be safe when I am in places I'm not supposed to be in. 

**Acceptance criteria**
- [x] Keys can be collected and are uniquely tied to a door.
- [x] Doors cannot be opened without a key.
- [x] Doors can be opened if the key is in the inventory.
- [ ] Doors can be locked (and unlocked) by the player

**Comment by ThePedroboy** [comment]
@KristofLenard12 This is already done - at least all of the points of the acceptance criteria, that is all already implemented. Door can require a pick up of a certain story clue (key) which will unlock the specific door.
